plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
}

group = "com.example.quick_usb"
version = "1.0-SNAPSHOT"

android {
    namespace = "com.example.quick_usb"
    compileSdk = 35

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
    }

    defaultConfig {
        minSdk = 21
    }
}
